<?php
/**
 * @var \Abbott\CustomerTwoFactorAuth\Block\LoginSecurity $block
 */
?>

<form class="form form-edit-account" action="<?= $escaper->escapeUrl($block->getUrl('*/*/disablepost')); ?>" method="post" id="form-validate" autocomplete="off" data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey'); ?>
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Disable Two Factor Authentication')); ?></span></legend><br>

        <div class="field required">
            <label class="label" for="current-password"><span><?= $escaper->escapeHtml(__('Current Password')); ?></span></label>
            <div class="control">
                <input type="password" id="current-password" name="current-password" title="<?= $escaper->escapeHtmlAttr(__('Current Password')); ?>" class="input-text required-entry" data-validate="{required:true}" aria-required="true" required data-mage-init='{"mage/trim-input":{}}'>
            </div>
        </div>

        <div class="field required">
            <small><?= $escaper->escapeHtml(__('Enter your password to disable Two Factor Authentication')); ?></small>
        </div>
    </fieldset>

    <fieldset class="fieldset info"></fieldset>

    <div class="actions-toolbar">
        <div id="cancel-div">
            <a class="action" href="<?= $escaper->escapeUrl($block->getUrl('*/*')); ?>">
                <span>&larr; <?= $escaper->escapeHtml(__('Cancel')); ?></span>
            </a>
        </div>
        <div id="save-div">
            <button type="submit" class="action save primary" title="Save">
                <span><?= $escaper->escapeHtml(__('Save')); ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
